services:
  - type: web
    name: digibank-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: digibank-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: digibank-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: digibank-db
          property: password
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: digibank-db
    databaseName: digibank
    user: digibank_user
    plan: free
